### ISSUE TITLE
ModuleNotFoundError: No module named 'System'

### ISSUE THREAD

**Issue by kaixin-bai** [rnd-team-dev/plotoptix#23]
command:
```bash
python3 ~/plotoptix/examples/1_basics/0_try_plotoptix.py
```

error:
```bash
Traceback (most recent call last):
  File "0_try_plotoptix.py", line 2, in <module>
    from plotoptix import TkOptiX
  File "/home/kb/anaconda3/envs/ppd/lib/python3.6/site-packages/plotoptix/__init__.py", line 24, in <module>
    from plotoptix.npoptix import NpOptiX
  File "/home/kb/anaconda3/envs/ppd/lib/python3.6/site-packages/plotoptix/npoptix.py", line 15, in <module>
    from plotoptix.geometry import GeometryMeta
  File "/home/kb/anaconda3/envs/ppd/lib/python3.6/site-packages/plotoptix/geometry.py", line 15, in <module>
    from plotoptix._load_lib import load_optix
  File "/home/kb/anaconda3/envs/ppd/lib/python3.6/site-packages/plotoptix/_load_lib.py", line 17, in <module>
    from System import IntPtr, Int64
ModuleNotFoundError: No module named 'System'
```

command:
```bash
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import clr
>>> from System import String
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'System'
```

**Comment by robertsulej** [comment]
Could you, please, run

```
import clr
print(clr.__version__)
```
and post the output? Maybe you have a name clash with another clr module.
