### ISSUE TITLE
OptiX initialization failed.

### ISSUE THREAD

**Issue by rajashekhargithubb** [rnd-team-dev/plotoptix#26]
`
CUDAOutputBuffer destructor caught exception: CUDA call (cudaFreeHost(reinterpret_cast<void*>(m_host_zcopy_pixels)) ) failed with error: 'the provided PTX was compiled with an unsupported toolchain.' (c:\users\sulej\documents\visual studio 2017\projects\optix\cppsharpoptix7\cudaoutputbuffer.h:87)

CUDAOutputBuffer destructor caught exception: CUDA call (cudaFreeHost(reinterpret_cast<void*>(m_host_zcopy_pixels)) ) failed with error: 'the provided PTX was compiled with an unsupported toolchain.' (c:\users\sulej\documents\visual studio 2017\projects\optix\cppsharpoptix7\cudaoutputbuffer.h:87)

CUDAOutputBuffer destructor caught exception: CUDA call (cudaFreeHost(reinterpret_cast<void*>(m_host_zcopy_pixels)) ) failed with error: 'the provided PTX was compiled with an unsupported toolchain.' (c:\users\sulej\documents\visual studio 2017\projects\optix\cppsharpoptix7\cudaoutputbuffer.h:87)

CUDAOutputBuffer destructor caught exception: CUDA call (cudaFreeHost(reinterpret_cast<void*>(m_host_zcopy_pixels)) ) failed with error: 'the provided PTX was compiled with an unsupported toolchain.' (c:\users\sulej\documents\visual studio 2017\projects\optix\cppsharpoptix7\cudaoutputbuffer.h:87)

CUDAOutputBuffer destructor caught exception: CUDA call (cudaFreeHost(reinterpret_cast<void*>(m_host_zcopy_pixels)) ) failed with error: 'the provided PTX was compiled with an unsupported toolchain.' (c:\users\sulej\documents\visual studio 2017\projects\optix\cppsharpoptix7\cudaoutputbuffer.h:87)

[ERROR] (MainThread) Initial setup failed, see errors above.
[ERROR] (MainThread) Geometry setup failed.
[ERROR] (MainThread) Geometry setup failed.
[ERROR] (MainThread) Geometry setup failed.
[Py-C# interop]
OptiX initialization failed.
Unknown OptixResult code: Compatible device(s) not found / OptiX not initialized.
PathTracer destructor failed.
[ERROR] (MainThread) Camera setup failed.
[ERROR] (MainThread) Current camera is not set.
[ERROR] (MainThread) Need 3D coordinates for the new light.
[ERROR] (MainThread) Camera setup failed.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\rajas\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\work\personal\plotoptix\venv\lib\site-packages\plotoptix\npoptix.py", line 390, in run
    assert self._is_scene_created, "Scene is not ready, see initialization messages."
AssertionError: Scene is not ready, see initialization messages.
`
Os Windows 10

**Comment by robertsulej** [comment]
Please, use NVIDIA driver >= r465.

**Comment by rajashekhargithubb** [comment]
@robertsulej Thanks Its working, Fine If i use NVIDIA driver >=r465

**Comment by Bortrex** [comment]
What about linux ? same error with driver=525.147.05 and cuda 12

**Comment by robertsulej** [comment]
Please, use the newest driver. 525 is now below [requirements](https://github.com/rnd-team-dev/plotoptix?tab=readme-ov-file#system-requirements).
