### ISSUE TITLE
Video encoding library initialization failed, encoding features are not available.

### ISSUE THREAD

**Issue by leeyngdo** [rnd-team-dev/plotoptix#59]
Hello, thank you for the great work! I'm trying to run simplex.py on the remote server, but I encountered the following error:

**********************************************************************************
**********************************************************************************
Video encoding library initialization failed, encoding features are not available.
**********************************************************************************
**********************************************************************************
        [0]: NVIDIA GeForce RTX 2080 Ti
********************************************************************************

I'm working with an RTX 2080 Ti, Driver Version: 535.161.08 and CUDA Version: 12.2. Also FFmpeg == 7.0. What can I try to resolve this error? Thank you!

**Comment by robertsulej** [comment]
Your ffmpeg libs are apparently not visible to plotoptix. Let me check how the ffmpeg installation is now proceeding in linux, I'll let you know later today.

**Comment by leeyngdo** [comment]
Thank you for your fast response! I'm also considering downgrading FFmpeg, but I'm not sure if that will work..

**Comment by robertsulej** [comment]
I need to update the code to use ffmpeg API available with the 7.0 release. Tomorrow should be ready.

**Comment by leeyngdo** [comment]
Hello, could you let me know when it will be updated?

**Comment by robertsulej** [comment]
Sure, I'll let you know. There is some more to do since the new ffmpg dll is too large to include it in the package and the Windows binaries need changes.

**Comment by robertsulej** [comment]
Updated code is in [this branch](https://github.com/rnd-team-dev/plotoptix/tree/r0.18.2). It should work with ffmpeg 7 installed as in the README, with shared libs (both, windows and linux, are updated).

**Comment by leeyngdo** [comment]
Hi, thank you for the update! However, my error is still not resolved, so I'm trying a downgraded version of FFmpeg (5.1.4). I'll let you know the result.

**Comment by robertsulej** [comment]
OK, maybe something else is blocking you. Please, try plotoptix v0.18.1 and [ffmpeg 4.1.11](https://ffmpeg.org/download.html#build-linux). That ffmpeg was used to prepare several plotoptix release and is well tested.

**Comment by leeyngdo** [comment]
I downloaded ffmpeg 4.1.11 in [this page](https://ffmpeg.org/download.html#releases). Now I could import TkOptiX, but it outputs the following error when I run the example code

```python
import numpy as np
from plotoptix import TkOptiX

n = 1000000                                  # 1M points, better not try this with matplotlib
xyz = 3 * (np.random.random((n, 3)) - 0.5)   # random 3D positions
r = 0.02 * np.random.random(n) + 0.002       # random radii

plot = TkOptiX()
plot.set_data("my plot", xyz, r=r)
plot.show()
```

[0]: NVIDIA GeForce RTX 2080 Ti
        Selected devices: [0]
        Primary device: 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/anaconda3/envs/optix/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/optix/lib/python3.10/site-packages/plotoptix/npoptix.py", line 495, in run
    self._run_event_loop()
  File "/root/anaconda3/envs/optix/lib/python3.10/site-packages/plotoptix/tkoptix.py", line 166, in _run_event_loop
    self._root = tk.Tk()
  File "/root/anaconda3/envs/optix/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
minor Version (60) newer than tool (should be 59)
minor NvvmIRVersion (63) newer than tool (should be 58)
[ 2][    COMPILER]: COMPILE ERROR:

**Comment by robertsulej** [comment]
OK, now the issue is to configure the remote display. Please, try usual instructions, eg like [this one](https://raspberrypi.stackexchange.com/questions/99447/run-tkinter-gui-on-remote-machine-connected-by-ssh).

**Comment by leeyngdo** [comment]
Thanks! The following is the error message I got:

minor Version (60) newer than tool (should be 59)
minor NvvmIRVersion (63) newer than tool (should be 58)
[ 2][    COMPILER]: COMPILE ERROR: 

OPTIX_ERROR_INVALID_INPUT: Optix call 'optixModuleCreate( m_context, &m_module_compile_options, &m_pipeline_compile_options, ptx.data(), ptx.size(), log, &sizeof_log, &mnew )' failed: Modules.cpp:49)
Log:
COMPILE ERROR: 

and nothing is rendered in the screen:

<img width="453" alt="Screenshot 2024-05-27 at 5 00 07 PM" src="https://github.com/rnd-team-dev/plotoptix/assets/88715406/44b367ab-72c9-4725-b322-3ebd84785f1d">

I think this error might be related to [this version mismatch](https://forums.developer.nvidia.com/t/optix-8-module-creation-version-mismatch/272885), right?

**Comment by robertsulej** [comment]
Yes, the driver update should help. Shaders were compiled with CUDA 12.3 and it may require the driver release >= 545.23.

**Comment by leeyngdo** [comment]
Finally it works after I upgrade CUDA & NVIDIA driver. Thank you for your kind answer!

**Comment by robertsulej** [comment]
Great! I'll check what could be a problem with ffmpeg 7.0 in the new code and let you know.
