### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by Pizzanomicon** [rnd-team-dev/plotoptix#61]
`rt.set_rt_size([5760, 3240])` results in :
Exception in Tkinter callback
Traceback (most recent call last):
  File "d:\ProgramData\Miniconda3\envs\dev1\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "d:\ProgramData\Miniconda3\envs\dev1\lib\site-packages\plotoptix\tkoptix.py", line 572, in _gui_update_content
    self._gui_internal_image_update()
  File "d:\ProgramData\Miniconda3\envs\dev1\lib\site-packages\plotoptix\tkoptix.py", line 529, in _gui_internal_image_update
    pil_img = pil_img.resize((wc, hnew), Image.ANTIALIAS)
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

both set_rt_size() and set_uint() will result in this error.
I believe that ANTIALIAS has been deprecated, and should be replaced with PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS.

**Comment by robertsulej** [comment]
Hi Phil,

Thanks for pointing this out! I'll update the code later today and let you know.

**Comment by robertsulej** [comment]
Updated code is in [this branch](https://github.com/rnd-team-dev/plotoptix/tree/r0.18.2). Note this branch includes ffmpeg updated to v7.0 which is not yet functional in Linux, but in Windows will work fine.
Thanks again for spotting this issue!
