### ISSUE TITLE
ModuleNotFoundError: No module named 'System'

### ISSUE THREAD

**Issue by JGSVb** [rnd-team-dev/plotoptix#9]
I tried to install plotoptix denoiser, but this happends.
It can't find system module.

```
asv@kata:~$ sudo python3.8 -m plotoptix.install denoiser
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/plotoptix/__init__.py", line 24, in <module>
    from plotoptix.npoptix import NpOptiX
  File "/usr/local/lib/python3.8/site-packages/plotoptix/npoptix.py", line 16, in <module>
    from plotoptix._load_lib import load_optix, load_denoiser, PARAM_NONE_CALLBACK, PARAM_INT_CALLBACK
  File "/usr/local/lib/python3.8/site-packages/plotoptix/_load_lib.py", line 18, in <module>
    from System import IntPtr, Int64
ModuleNotFoundError: No module named 'System'
asv@kata:~$
```
The same happens when i try to install examples.

```
asv@kata:~$ sudo python3.8 -m plotoptix.install examples
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.8/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.8/site-packages/plotoptix/__init__.py", line 24, in <module>
    from plotoptix.npoptix import NpOptiX
  File "/usr/local/lib/python3.8/site-packages/plotoptix/npoptix.py", line 16, in <module>
    from plotoptix._load_lib import load_optix, load_denoiser, PARAM_NONE_CALLBACK, PARAM_INT_CALLBACK
  File "/usr/local/lib/python3.8/site-packages/plotoptix/_load_lib.py", line 18, in <module>
    from System import IntPtr, Int64
ModuleNotFoundError: No module named 'System'
```

I am using python3.8. Linux Mint 19.1 Tessa

**Comment by robertsulej** [comment]
This means you passed OK through the line `import clr`, which makes the `System` module available. Could you please let me know what happens if you try this in python:

```
import clr
from System import String
```

I can see on [pythonnet page](https://github.com/pythonnet/pythonnet) there are issues with python 3.8. If possible, please try python 3.7.

**Comment by robertsulej** [comment]
No activity - closing. Feel free to reopen if something new happens on this topic.
